sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
services:
- docker
before_install:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
install:
- docker pull neo4j
- docker run -d --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=none
  --volume=$HOME/neo4j/data:/data neo4j
- cd $TRAVIS_BUILD_DIR/scripts/linux/deb/ && ./build_deps.sh
- cd $TRAVIS_BUILD_DIR
script:
- gcc --version
- ldd --version
- make tests
- cd $TRAVIS_BUILD_DIR/neocpp/test && ./neo4j_test
- cd $TRAVIS_BUILD_DIR && sudo make install
- cd $TRAVIS_BUILD_DIR && sudo make uninstall
